apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-fdse
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0014-tenant/tkrw-pr712-0075-0014-app/devfile-sample-fdse@sha256:a24c0ccc50d04c7e0defbc75b7e609bc1f90da25ad3c3e5f03e0e1720a4e658f
        name: my-nodejs
        resources: {}
status: {}
